### ISSUE TITLE
Pabot error with Python 3.8

### ISSUE THREAD

**Issue by Ladrick** [ppodgorsek/docker-robot-framework#271] opened 2020-04-29 14:37 UTC
Got this error from the Microsoft Azure container log after the latest changes were made.
My guess it's related to the Python version migration from 3.7 to 3.8

    Traceback (most recent call last):
        File "/usr/local/bin/pabot", line 8, in <module> sys.exit(main())
        File "/usr/local/lib/python3.8/site-packages/pabot/pabot.py", line 1600, in main _parallel_execute(items, pabot_args['processes'])
        File "/usr/local/lib/python3.8/site-packages/pabot/pabot.py", line 1291, in _parallel_execute pool = ThreadPool(processes)
        File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 922, in __init__ Pool.__init__(self, processes, initializer, initargs)
        File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 196, in __init__ self._change_notifier = self._ctx.SimpleQueue()
        File "/usr/local/lib/python3.8/multiprocessing/context.py", line 113, in SimpleQueue return SimpleQueue(ctx=self.get_context())
        File "/usr/local/lib/python3.8/multiprocessing/queues.py", line 336, in __init__ self._rlock = ctx.Lock()
        File "/usr/local/lib/python3.8/multiprocessing/context.py", line 68, in Lock return Lock(ctx=self.get_context())
        File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__ SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
        File "/usr/local/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__ sl = self._semlock = _multiprocessing.SemLock(
    OSError: [Errno 95] Not supported

**Comment by ppodgorsek** [comment] 2020-05-02 13:58
Thank you for opening this issue @Ladrick . Could you provide more details about your test script in order to reproduce the issue please?

**Comment by ppodgorsek** [comment] 2020-05-11 20:24
After doing some research, it looks like this could be related to where the tests were run from. For example, AWS does not provide access to `/dev/shm` in Lambda, which in turn would cause that issue.

See:

* https://forums.aws.amazon.com/thread.jspa?threadID=219962
* https://stackoverflow.com/questions/34005930/multiprocessing-semlock-is-not-implemented-when-running-on-aws-lambda

@Ladrick, could you provide more details please?

**Comment by Ladrick** [comment] 2020-05-12 09:23
Sorry for the late reply. Didn't have any time to switch to the latest build and check if the problem still persists.
Pretty much everything is standard. 
An Azure docker container.
76 tests run in 4 parallel threads using the tags to run them.
3 shares:
1)For tests (/opt/robotframework/tests)
2)For reports (/opt/robotframework/reports)
3)/dev/shm | { "shareName": "rfshmshare", "readOnly": false, (Until this share was added, Firefox browser refused to work for some reason)

Having absolutely no problems with version 3.5.0.
However after switching to the latest one, the tests just fail with the above mentioned errors.

**Comment by UltimateDogg** [comment] 2020-06-25 15:28
if checking out the current repo and replacing the base image with 3.7-alpine3.11 instead of 3.8-alpine3.11 do you get the same issue? Trying to determine if its python as like ppodgorsek said that looks like an issue others have faced  in places with no dev/shm and its odd that pabot works in the old version. If it still doesnt work would have to see if its pabot regression or maybe alpine change that caused it

**Comment by ppodgorsek** [comment] 2020-07-05 17:38
I upgraded Pabot to its latest version (1.8.0), maybe this will help.

**Comment by Ladrick** [comment] 2020-08-10 12:15
Tried with the latest version.
Sadly the issue still persists.

**Comment by ppodgorsek** [comment] 2020-11-16 19:41
Unfortunately, I still cannot reproduce this issue and have no means to test it myself.

I upgraded Pabot to version 1.10.0 today; there seems to have been some fixes related to multithreading, hopefully they'll solve your problem.
Additionally, I upgraded the base image to python:3.9.0-alpine3.12.

**Comment by ppodgorsek** [comment] 2021-03-15 14:12
Closing this ticket, as we cannot reproduce it. Consider reopening it with updated information using the latest image if necessary.

**Closed by ppodgorsek** 2021-03-15 14:12 UTC
Labels: bug, invalid / cannot reproduce
