### ISSUE TITLE
SimpleTest with chrome failed ?

### ISSUE THREAD

**Issue by benouillor** [ppodgorsek/docker-robot-framework#25] opened 2017-09-17 03:04 UTC
Hi,

I'm testing your docker image with a simple ROBOT test like [Simple.robot.txt](https://github.com/ppodgorsek/docker-robot-framework/files/1308797/Simple.robot.txt)

But i get error: **WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally**

Robot debug do not help very much: 
[debug.txt](https://github.com/ppodgorsek/docker-robot-framework/files/1308801/debug.txt)

And inside image chrome log file, i get a lot of: 
DevTools Request: 127.0.0.1:12585/json/version. DevTools request failed

Can you help me or send me a simple working robot test sample ?

thanks !

**Comment by ppodgorsek** [comment] 2017-09-25 22:51
I tried on several configurations and cannot reproduce this issue. Are you sure you are using the latest version?

This is what I tried:
  1. Put the `Simple.robot.txt` file in /opt/docker/robot/tests (the folder name doesn't matter)
  2. `git pull ppodgorsek/robot-framework`
  3. `docker run -v /opt/docker/robot/reports:/opt/robotframework/reports:Z -v /opt/docker/robot/tests:/opt/robotframework/tests:Z -e BROWSER=chrome ppodgorsek/robot-framework:latest`

The result I have is:

    Tests.Simple.robot                                                            
    ==============================================================================
    Visit Google                                                          | PASS |
    ------------------------------------------------------------------------------
    Tests.Simple.robot                                                    | PASS |
    1 critical test, 1 passed, 0 failed
    1 test total, 1 passed, 0 failed
    ==============================================================================

Do these steps solve the issue for you?

**Comment by ppodgorsek** [comment] 2017-11-20 11:12
Closing this issue as it was no reproduced and no update was received for the last two months.

**Closed by ppodgorsek** 2017-11-20 11:12 UTC
Labels: bug

**Comment by nidaanjum89** [comment] 2022-03-21 17:00
I have the same issue and I have also tried your troubleshooting option for chromium. But still the same. I have also commented with all detailed information on my issue to you please have a look.
